spring.datasource.url=jdbc:mysql://localhost:3306/quanlythuchi
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=nuXLpuhA2FG2wULdwEXTFkgXOz42Z16Nj5qIcpJn7KZ
jwt.expiration=86400000

# Thông tin đơn vị in trên phiếu
voucher.company.name=Công ty TNHH Giải Pháp Tài Chính Việt Nam
voucher.company.address=Lầu 5, 123 Nguyễn Thị Minh Khai, Quận 3, TP. Hồ Chí Minh