spring.datasource.url=jdbc:mysql://localhost:3306/quanlythuchi
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=nuXLpuhA2FG2wULdwEXTFkgXOz42Z16Nj5qIcpJn7KZ
jwt.expiration=86400000

# ThÃ´ng tin Ä‘Æ¡n vá»‹ in trÃªn phiáº¿u
voucher.company.name=Công Ty Gi?i Pháp Toàn C?u Doanh Nghi?p GESO
voucher.company.address=GESO Office, 62 ?. Nguy?n Th??ng Hi?n, H?nh Thông, H? Chí Minh 700000